#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define SEED 0
#define NUM_ITERATIONS 5000
#define NUM_FISH 100000
#define STEP_IND 0.1
#define INITIAL_WT 10
#define MINIMISE_FITNESS_FN true
#define EUCLIDEAN_DOMAIN_WIDTH 200
#define SHUBERT_DOMAIN_WIDTH 20
#define RASTRIGIN_DOMAIN_WIDTH 10.24

#endif